- name: Update Proxmox Server
  hosts: proxmox
  become: yes
  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        clean: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required get_md5=no
      register: reboot_required

    - name: Reboot server if required
      reboot:
        msg: "Rebooting to apply updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime 
      when: reboot_required.stat.exists

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 10
        timeout: 300
      when: reboot_required.stat.exists